### your site title here

title: Paulo Diovani
description: A personal blog about romance, technology and tabletop games
repository: github.com/paulodiovani/blog.diovani.com

# used by Atom Feed
url: http://blog.diovani.com
author: Paulo Diovani <paulo AT diovani DOT com>

# do not display future posts
future: false

social:
  email: paulo AT diovani DOT com
  linkedin: linkedin.com/in/paulodiovani
  twitter: paulodiovani
  github: github.com/paulodiovani

highlighter: rouge
markdown: kramdown

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Tracker
#analytics: UA-83979019-1

# Comments
disqus-shortname: paulo-diovani

#optimization
#compress.html
compress_html:
  clippings: [html, div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

sass:
 style: compressed

exclude:
- README.md

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
